export const MAINTENANCE_TREATMENTS = {
  PAVEMENT_MANUAL_PATCHING: "PAVEMENT_MANUAL_PATCHING",
  PAVEMENT_MACHINE_PATCHING: "PAVEMENT_MACHINE_PATCHING",
  PAVEMENT_SPRAY_PATCHING: "PAVEMENT_SPRAY_PATCHING",
  PAVEMENT_ROUT_AND_SEAL_CRACKS: "PAVEMENT_ROUT_AND_SEAL_CRACKS",
  PAVEMENT_CHIP_SEAL: "PAVEMENT_CHIP_SEAL",
  SHOULDERS_MANUAL_PATCHING: "SHOULDERS_MANUAL_PATCHING",
  SHOULDERS_MACHINE_PATCHING: "SHOULDERS_MACHINE_PATCHING",
  SHOULDERS_ROUT_AND_SEAL_CRACKS: "SHOULDERS_ROUT_AND_SEAL_CRACKS",
  SHOULDERS_CHIP_SEAL: "SHOULDERS_CHIP_SEAL",
};

export const DISTRESS = {
  SURFACE_DEFECTS_RAVELLING_AND_C_AGG_LOSS:
    "SURFACE_DEFECTS_RAVELLING_AND_C_AGG_LOSS",
  SURFACE_DEFECTS_FLUSHING: "SURFACE_DEFECTS_FLUSHING",
  SURFACE_DEFORMATIONS_RIPPLING_AND_SHOVING:
    "SURFACE_DEFORMATIONS_RIPPLING_AND_SHOVING",
  SURFACE_DEFORMATIONS_WHEEL_TRACK_RUTTING:
    "SURFACE_DEFORMATIONS_WHEEL_TRACK_RUTTING",
  SURFACE_DEFORMATIONS_DISTORTION: "SURFACE_DEFORMATIONS_DISTORTION",
  LONGITUDINAL_WHEEL_TRACK_SINGLE_AND_MULTIPLE:
    "LONGITUDINAL_SINGLE_AND_MULTIPLE",
  LONGITUDINAL_WHEEL_TRACK_ALLIGATOR: "LONGITUDINAL_ALLIGATOR",
  CENTER_LINE_SINGLE_AND_MULTIPLE: "CENTER_LINE_SINGLE_AND_MULTIPLE",
  CENTER_LINE_ALLIGATOR: "CENTER_LINE_ALLIGATOR",
  PAVEMENT_EDGE_SINGLE_AND_MULTIPLE: "PAVEMENT_EDGE_SINGLE_AND_MULTIPLE",
  PAVEMENT_EDGE_ALLIGATOR: "PAVEMENT_EDGE_ALLIGATOR",
  TRANSVERSE_HALF_FULL_AND_MULTIPLE: "TRANSVERSE_HALF_FULL_AND_MULTIPLE",
  TRANSVERSE_ALLIGATOR: "TRANSVERSE_ALLIGATOR",
  LONGITUDINAL_MEANDER_AND_MIDLANE: "LONGITUDINAL_MEANDER_AND_MIDLANE",
  RANDOM: "RANDOM",
};

export const SEVERITY_AND_DENSITY_OF_DISTRESS = {
  VERY_SLIGHT: "Very Slight",
  SLIGHT: "Slight",
  Maderate: "Moderate",
  Severe: "Severe",
  VERY_SEVERE: "Very Severe",
  FEW: "Few",
  INTERMITTENT: "Intermittent",
  FREQUENT: "Frequent",
  EXTENSIVE: "Extensive",
  THROUGHOUT: "Throughout",
};

// export const DENSITY_OF_DISTRESS = {
//   FEW: "Few",
//   INTERMITTENT: "Intermittent",
//   FREQUENT: "Frequent",
//   EXTENSIVE: "Extensive",
//   THROUGHOUT: "Throughout",
// };
