export const MAINTENANCE_TREATMENTS = {
  PAVEMENT_MANUAL_PATCHING: "PAVEMENT_MANUAL_PATCHING",
  PAVEMENT_MACHINE_PATCHING: "PAVEMENT_MACHINE_PATCHING",
  PAVEMENT_SPRAY_PATCHING: "PAVEMENT_SPRAY_PATCHING",
  PAVEMENT_ROUT_AND_SEAL_CRACKS: "PAVEMENT_ROUT_AND_SEAL_CRACKS",
  PAVEMENT_CHIP_SEAL: "PAVEMENT_CHIP_SEAL",
  SHOULDERS_MANUAL_PATCHING: "SHOULDERS_MANUAL_PATCHING",
  SHOULDERS_MACHINE_PATCHING: "SHOULDERS_MACHINE_PATCHING",
  SHOULDERS_ROUT_AND_SEAL_CRACKS: "SHOULDERS_ROUT_AND_SEAL_CRACKS",
  SHOULDERS_CHIP_SEAL: "SHOULDERS_CHIP_SEAL",
};
